name: Node.js CI

on:
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: 'Create .env file'
      run: |
        echo '${{ secrets.APP_ENV_FILE }}' > .env
        echo '${{ secrets.SERVER_ENV_FILE }}' > server/.env
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run build
    - run: cd server && pm2 delete logea-api || true && pm2 start server.js --name "logea-api"